# Cloud Build pipeline
# Bu betik GitHub push tetiginde Docker imajini build eder, Artifact Registry'ye push eder
# ve GKE uzerinde deploymentin imajini gunceller. Tum yorumlar ASCII formatindadir.

substitutions:
  _REGION: us-central1
  _ARTIFACT_REPO: qr-photo-backend
  _IMAGE_NAME: qr-photo-backend
  _CLUSTER: qr-photo-dev-autopilot
  _LOCATION: us-central1
  _NAMESPACE: qr-photo-dev-namespace
  _DEPLOYMENT: qr-photo-dev-deployment
  _CONTAINER: qr-photo-dev-app

# Build islemleri icin maksimum calisma suresi.
timeout: 1200s

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
      - "-f"
      - backend/Dockerfile
      - .
  
  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
  
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Tag latest
    entrypoint: gcloud
    args:
      - artifacts
      - docker
      - tags
      - add
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest"
  
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Configure kubectl
    entrypoint: gcloud
    args:
      - container
      - clusters
      - get-credentials
      - ${_CLUSTER}
      - --region
      - ${_LOCATION}
      - --project
      - $PROJECT_ID
  
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Update deployment image
    entrypoint: kubectl
    args:
      - --namespace=${_NAMESPACE}
      - set
      - image
      - deployment/${_DEPLOYMENT}
      - ${_CONTAINER}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$SHORT_SHA
  
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Wait rollout
    entrypoint: kubectl
    args:
      - --namespace=${_NAMESPACE}
      - rollout
      - status
      - deployment/${_DEPLOYMENT}
      - --timeout=300s

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$SHORT_SHA"