# Terraform icin Cloud Build pipeline
# Bu pipeline _ENV ve _TFVARS_URI substitutions degerleri ile tek ortam icin fmt/validate/plan adimlarini Calistirir.

substitutions:
  _TF_VERSION: "1.6.6"
  _STATE_BUCKET: "qr-photo-tf-state-bucket"
  _STATE_PREFIX: "qr-photo/terraform"
  _ENV: "dev"
  _TFVARS_URI: "gs://qr-photo-tf-state-bucket/tfvars/dev.tfvars"
  _BASE_TFVARS_URI: "gs://qr-photo-tf-state-bucket/tfvars/base.tfvars"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  - id: terraform-fmt
    name: "hashicorp/terraform:${_TF_VERSION}"
    entrypoint: sh
    args:
      - -c
      - terraform -chdir=infra/terraform/gcp fmt -recursive -check

  - id: fetch-tfvars-${_ENV}
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: sh
    args:
      - -c
      - |
        set -eu
        gsutil cp ${_BASE_TFVARS_URI} /workspace/base.tfvars
        gsutil cp ${_TFVARS_URI} /workspace/${_ENV}.tfvars

  - id: terraform-init-plan-${_ENV}
    name: "hashicorp/terraform:${_TF_VERSION}"
    entrypoint: sh
    args:
      - -c
      - |
        set -eu
        terraform -chdir=infra/terraform/gcp init \
          -backend-config="bucket=${_STATE_BUCKET}" \
          -backend-config="prefix=${_STATE_PREFIX}/${_ENV}" \
          -input=false
        terraform -chdir=infra/terraform/gcp workspace select ${_ENV} || terraform -chdir=infra/terraform/gcp workspace new ${_ENV}
        terraform -chdir=infra/terraform/gcp validate
        terraform -chdir=infra/terraform/gcp plan \
          -input=false \
          -var-file=/workspace/base.tfvars \
          -var-file=/workspace/${_ENV}.tfvars \
          -out="/workspace/tfplan-${_ENV}.out"
        terraform -chdir=infra/terraform/gcp show -no-color \
          "/workspace/tfplan-${_ENV}.out" > "/workspace/tfplan-${_ENV}.txt"

artifacts:
  objects:
    location: "gs://${_STATE_BUCKET}/${_STATE_PREFIX}/${_ENV}/plans"
    paths:
      - tfplan-${_ENV}.out
      - tfplan-${_ENV}.txt
