# Cloud Build pipeline
# Bu betik GitHub push tetiginde Docker imajini build eder, Artifact Registry'e push eder
# ve GKE uzerinde deploymentin imajini gunceller. Tum yorumlar ASCII formatindadir.
substitutions:
  # _REGION: Artifact Registry ve imaj build islemlerinin yapilacagi bolge.
  _REGION: europe-west1
  # _ARTIFACT_REPO: Artifact Registry depo kimligi (Terraform default: qr-photo-backend).
  _ARTIFACT_REPO: qr-photo-backend
  # _IMAGE_NAME: Docker imaj adi (uygulama komponent adi).
  _IMAGE_NAME: qr-photo-backend
  # _CLUSTER: GKE cluster adi (Terraform ciktisi: <project>-<env>-autopilot).
  _CLUSTER: qr-photo-dev-autopilot
  # _LOCATION: GKE cluster bolgesi.
  _LOCATION: europe-west1
  # _NAMESPACE: Kubernetes namespace adi (Terraform ciktisi: <project>-<env>-namespace).
  _NAMESPACE: qr-photo-dev-namespace
  # _DEPLOYMENT: Guncellenecek deployment adi (Terraform ciktisi: <project>-<env>-deployment).
  _DEPLOYMENT: qr-photo-dev-deployment
  # _CONTAINER: Deployment icindeki container adi (Terraform ciktisi: <project>-<env>-app).
  _CONTAINER: qr-photo-dev-app

# Build islemleri icin maksimum calisma suresi.
timeout: 1200s

# Docker imajinin tam path'i. Cloud Build bunu otomatik olusturmak icin kullanir.
options:
  substitution_option: ALLOW_LOOSE

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - "-t"
      - "-docker.pkg.dev///:"
      - "-f"
      - backend/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - "-docker.pkg.dev///:"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Tag latest
    entrypoint: gcloud
    args:
      - artifacts
      - docker
      - tags
      - add
      - "-docker.pkg.dev///:"
      - "-docker.pkg.dev///:latest"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Configure kubectl
    entrypoint: gcloud
    args:
      - container
      - clusters
      - get-credentials
      - 
      - --region
      - 
      - --project
      - 

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Update deployment image
    entrypoint: kubectl
    args:
      - --namespace=
      - set
      - image
      - deployment/
      - =-docker.pkg.dev///:

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Wait rollout
    entrypoint: kubectl
    args:
      - --namespace=
      - rollout
      - status
      - deployment/
      - --timeout=300s

images:
  - "-docker.pkg.dev///:"
