name: Terraform CI

on:
  pull_request:
    paths:
      - 'infra/terraform/**'

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
      - name: Terraform Format
        run: terraform -chdir=infra/terraform/gcp fmt -check
      - name: Terraform Init (no backend)
        run: terraform -chdir=infra/terraform/gcp init -backend=false
      - name: Terraform Validate
        run: terraform -chdir=infra/terraform/gcp validate
